export const data = [
  {
    title: 'DAO Voting',
    description: `Participate in making decisions for the community via DAO voting.`,
    link: `/governance`,
  },
  {
    title: 'Research Forum',
    description: `Join forums to discuss your ideas with community members.`,
    link: `https://medium.com/@daowakanda`,
  },
];

export const dataTwo = [
  {
    title: 'Twitter',
    description: `Follow us @daowakanda`,
    link: `https://twitter.com/DaoWakanda`,
  },
  {
    title: 'Discord',
    description: `Ask questions`,
    link: `/`,
  },
  {
    title: 'Telegram',
    description: `Join the community`,
    link: `https://t.me/daowakanda`,
  },
];
export const proposalsData = [
  {
    id: 1,
    title: 'Algorand Event',
    yesVote: 7,
    noVote:1,
    tag: '2x3er3',
    isActive: true,
    description: `Lorem ipsum dolor sit amet consectetur. Cursus lorem viverra non commodo etiam a viverra. Dictum egestas eget feugiat sit nullam integer.`,
    end_time: `Ends in 6h:38m:34s`,
    created_on: `6h:38m:34s`,
    wallet_address: `2a4e4rt4`,
  },
  {
    id: 2,
    title: 'Wakanda Event',
    yesVote: 2,
    noVote:6,
    tag: '2x3er3',
    isActive: false,
    description: `Lorem ipsum dolor sit amet consectetur. Cursus lorem viverra non commodo etiam a viverra. Dictum egestas eget feugiat sit nullam integer.`,
    end_time: `05th July 2024, 05:00pm`,
    created_on: `6h:38m:34s`,
    wallet_address: `2a4e4rt4`,
  },
  {
    id: 3,
    title: 'Algorand Taraba Event',
    yesVote: 9,
    noVote:3,
    tag: '2x3er3',
    isActive: false,
    description: `Lorem ipsum dolor sit amet consectetur. Cursus lorem viverra non commodo etiam a viverra. Dictum egestas eget feugiat sit nullam integer.`,
    end_time: `05th July 2024, 05:00pm`,
    created_on: `6h:38m:34s`,
    wallet_address: `2a4e4rt4`,
  },
  {
    id: 4,
    title: 'Daowakanda Event',
    yesVote: 14,
    noVote:16,
    tag: '2x3er3',
    isActive: true,
    description: `Lorem ipsum dolor sit amet consectetur. Cursus lorem viverra non commodo etiam a viverra. Dictum egestas eget feugiat sit nullam integer.`,
    end_time: `Ends in 6h:38m:34s`,
    created_on: `6h:38m:34s`,
    wallet_address: `2a4e4rt4`,
  },
  {
    id: 5,
    title: 'Algorand Taraba Event',
    yesVote: 9,
    noVote:4,
    tag: '2x3er3',
    isActive: false,
    description: `Lorem ipsum dolor sit amet consectetur. Cursus lorem viverra non commodo etiam a viverra. Dictum egestas eget feugiat sit nullam integer.`,
    end_time: `05th July 2024, 05:00pm`,
    created_on: `6h:38m:34s`,
    wallet_address: `2a4e4rt4`,
  },
  {
    id: 6,
    title: 'Daowakanda Event',
    yesVote: 20,
    noVote:6,
    tag: '2x3er3',
    isActive: true,
    description: `Lorem ipsum dolor sit amet consectetur. Cursus lorem viverra non commodo etiam a viverra. Dictum egestas eget feugiat sit nullam integer.`,
    end_time: `Ends in 6h:38m:34s`,
    created_on: `6h:38m:34s`,
    wallet_address: `2a4e4rt4`,
  },
  {
    id: 7,
    title: 'Algorand Taraba Event',
    yesVote: 9,
    noVote:41,
    tag: '2x3er3',
    isActive: false,
    description: `Lorem ipsum dolor sit amet consectetur. Cursus lorem viverra non commodo etiam a viverra. Dictum egestas eget feugiat sit nullam integer.`,
    end_time: `05th July 2024, 05:00pm`,
    created_on: `6h:38m:34s`,
    wallet_address: `2a4e4rt4`,
  },
  {
    id: 8,
    title: 'Daowakanda Event',
    yesVote: 20,
    noVote:62,
    tag: '2x3er3',
    isActive: true,
    description: `Lorem ipsum dolor sit amet consectetur. Cursus lorem viverra non commodo etiam a viverra. Dictum egestas eget feugiat sit nullam integer.`,
    end_time: `Ends in 6h:38m:34s`,
    created_on: `6h:38m:34s`,
    wallet_address: `2a4e4rt4`,
  },
  {
    id: 9,
    title: 'Rand Fest Event',
    yesVote: 9,
    noVote:4,
    tag: '2x3er3',
    isActive: false,
    description: `Lorem ipsum dolor sit amet consectetur. Cursus lorem viverra non commodo etiam a viverra. Dictum egestas eget feugiat sit nullam integer.`,
    end_time: `05th July 2024, 05:00pm`,
    created_on: `6h:38m:34s`,
    wallet_address: `2a4e4rt4`,
  },
  {
    id: 10,
    title: 'Daowakanda Event',
    yesVote: 20,
    noVote:6,
    tag: '2x3er3',
    isActive: true,
    description: `Lorem ipsum dolor sit amet consectetur. Cursus lorem viverra non commodo etiam a viverra. Dictum egestas eget feugiat sit nullam integer.`,
    end_time: `Ends in 6h:38m:34s`,
    created_on: `6h:38m:34s`,
    wallet_address: `2a4e4rt4`,
  },
  {
    id: 11,
    title: 'Algorand Taraba Event',
    yesVote: 9,
    noVote:41,
    tag: '2x3er3',
    isActive: false,
    description: `Lorem ipsum dolor sit amet consectetur. Cursus lorem viverra non commodo etiam a viverra. Dictum egestas eget feugiat sit nullam integer.`,
    end_time: `05th July 2024, 05:00pm`,
    created_on: `6h:38m:34s`,
    wallet_address: `2a4e4rt4`,
  },
  {
    id: 12,
    title: 'Hackthon Event',
    yesVote: 20,
    noVote:62,
    tag: '2x3er3',
    isActive: true,
    description: `Lorem ipsum dolor sit amet consectetur. Cursus lorem viverra non commodo etiam a viverra. Dictum egestas eget feugiat sit nullam integer.`,
    end_time: `Ends in 6h:38m:34s`,
    created_on: `6h:38m:34s`,
    wallet_address: `2a4e4rt4`,
  },
]